# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      # Group Astro framework and its integrations
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
        update-types:
          - 'minor'
          - 'patch'

      # Group React ecosystem
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
          - '@nanostores/react'
        update-types:
          - 'minor'
          - 'patch'

      # Group Vercel packages
      vercel:
        patterns:
          - '@vercel/*'
        update-types:
          - 'minor'
          - 'patch'

      # Group testing tools
      testing:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - '@testing-library/*'
          - 'happy-dom'
        update-types:
          - 'minor'
          - 'patch'

      # Group development tools
      dev-tools:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - 'prettier*'
          - 'typescript'
          - 'husky'
          - 'lint-staged'
          - 'vite'
          - '@vitejs/*'
        update-types:
          - 'minor'
          - 'patch'

      # Group Supabase packages
      supabase:
        patterns:
          - '@supabase/*'
        update-types:
          - 'minor'
          - 'patch'

      # Group remaining production dependencies (minor/patch only)
      production-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - 'astro'
          - '@astrojs/*'
          - 'react*'
          - '@types/react*'
          - '@vercel/*'
          - '@supabase/*'
          - 'vitest*'
          - '@vitest/*'
          - '@testing-library/*'
          - 'eslint*'
          - '@typescript-eslint/*'
          - 'prettier*'
          - 'typescript'
          - 'husky'
          - 'lint-staged'
          - 'vite'
          - '@vitejs/*'
        update-types:
          - 'minor'
          - 'patch'

  # Monitor GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    groups:
      # Group all GitHub Actions updates together
      github-actions:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
